In [4]:
### Embeddings
### text to numbers
from sklearn.feature_extraction.text import TfidfVectorizer
docs =[" i love Cats","i love dogs",]
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(docs)
print(X.toarray())

[[0.81480247 0.         0.57973867]
 [0.         0.81480247 0.57973867]]


In [5]:
DC1 = ["saddam is good man","saddam need more money","samina is saddam wife"]
TF = TfidfVectorizer()
X = TF.fit_transform(DC1)
print(X.toarray())

[[0.5844829  0.44451431 0.5844829  0.         0.         0.
  0.34520502 0.         0.        ]
 [0.         0.         0.         0.54645401 0.54645401 0.54645401
  0.32274454 0.         0.        ]
 [0.         0.44451431 0.         0.         0.         0.
  0.34520502 0.5844829  0.5844829 ]]


In [21]:
embedding = model.encode(sentence)
print(embedding.shape)

(3, 768)


In [16]:
embedding[1 ]

array([-4.23495956e-02, -2.77895667e-02,  9.33127403e-02, -1.81870256e-02,
        2.99826823e-02,  4.11639642e-03,  1.18604228e-01, -4.54276949e-02,
        9.71825644e-02,  4.72235270e-02, -6.09563738e-02, -3.17669064e-02,
       -1.11800833e-02,  9.63868760e-03,  1.41879646e-02,  1.25937313e-01,
        4.94478010e-02, -5.72024174e-02, -3.29677947e-03, -1.58702005e-02,
       -9.86857414e-02,  8.33285823e-02, -4.52826172e-02,  3.03533021e-02,
       -1.14900380e-01,  5.62826311e-03,  6.21665688e-03,  3.33773345e-02,
       -2.59833992e-03, -1.84060484e-02, -6.58555478e-02,  6.58262074e-02,
        2.52019130e-02, -1.75801683e-02, -1.37985060e-02, -4.95407283e-02,
       -3.20819463e-03, -5.27873188e-02,  1.09312423e-02,  4.25650738e-02,
       -1.86797846e-02, -1.94839444e-02,  2.80539785e-02, -2.25336906e-02,
       -4.30564545e-02, -2.40935758e-02, -2.30475962e-02, -4.00600769e-02,
        9.84049216e-02,  2.20233388e-02,  1.68625335e-03, -1.61642935e-02,
       -8.19773450e-02,  

In [22]:
#FAISS Its a open source lab foe vector deatebase  devlope by facebook

!pip install faiss-cpu

In [23]:
!pip install faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 62.7 MB/s eta 0:00:00


In [24]:
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

In [25]:
model = SentenceTransformer('all-MiniLM-L6-v2')
print(model)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Normalize()
)


In [26]:
doc =[
    "The cat is on mat",
    "Dogs is man good man",
    "Saddam is like food ",
    "i love cricket",
    "Football is good game "
]
print(doc)

['The cat is on mat', 'Dogs is man good man', 'Saddam is like food ', 'i love cricket', 'Football is good game ']


In [29]:
em = model.encode(doc)
print(em)


[[ 0.10517562 -0.00819881 -0.01237991 ...  0.00197502  0.01338795
   0.06251504]
 [-0.04959108 -0.00699434  0.06626564 ... -0.02101756 -0.00865409
   0.04345187]
 [ 0.06217473  0.02708227  0.04210168 ... -0.00714629  0.05833939
  -0.01446362]
 [ 0.03202339  0.04759502 -0.01514222 ...  0.01212579  0.04952044
  -0.06025093]
 [ 0.00186025 -0.00140602 -0.00302453 ...  0.02975256  0.05636867
   0.01622608]]


In [30]:
len(em[0])

384

In [31]:
dim = em.shape[1]
print(dim)

384


In [32]:
index = faiss.IndexFlatL2(dim)
print(index)

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x7e868afd4a50> >


In [33]:
index.add(em)
print(index.ntotal)

5


In [44]:
#Query1 = "is the any thing releated to cricket? "
Query1   = "need animla story"
query_em = model.encode([Query])
print(query_em)


[[-4.66766767e-02  6.30240515e-02 -6.79141060e-02  1.24102093e-01
  -1.49855912e-01  1.61892474e-02  3.31046507e-02 -3.58530022e-02
   1.81630962e-02  3.76975685e-02  3.54732350e-02  9.23815090e-03
   2.45283414e-02  6.04577437e-02 -5.91403898e-03  4.41666134e-02
   7.62452791e-03 -8.61384906e-03 -5.72044253e-02 -8.58088657e-02
   2.73795798e-02 -6.84763044e-02  4.00081389e-02  6.91826502e-03
  -6.02038503e-02 -1.76896472e-02 -7.45320097e-02 -2.09433492e-02
  -7.40124146e-03 -1.04111202e-01 -6.41424432e-02  5.08270562e-02
   9.74467397e-02 -5.22124618e-02  2.18985807e-02  3.45412493e-02
   8.98824725e-03  3.22949924e-02 -4.34206100e-03  2.01713350e-02
   1.09952036e-02 -4.08149809e-02  4.60296161e-02 -3.81575190e-02
  -1.05925389e-02 -6.33407235e-02 -6.06816448e-02  6.44180505e-03
   2.64163525e-03  3.00173014e-02 -7.39861056e-02  2.49588247e-02
   3.36144343e-02 -6.48984909e-02 -1.02319652e-02 -4.44804244e-02
  -1.72119923e-02 -4.08896282e-02  7.40639027e-03 -3.32098641e-02
   2.87565

In [45]:
k=2
distance, indics = index.search(query_em,k)
print(distance)
print(indics)

[[1.721422  1.7928715]]
[[1 2]]


In [46]:
for i in indics[0]:
    print(doc[i])

Dogs is man good man
Saddam is like food 
